apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret

metadata:
  name: external-secrets-demo
  namespace: external-secrets

spec:
  refreshInterval: 1m
  secretStoreRef:
    kind: SecretStore
    name: external-secrets-demo

  target:
    name: external-secrets-demo
    creationPolicy: Owner
  data:
  - secretKey: sample-secret
    remoteRef:
      key: secret/sample-secret
  - secretKey: sample-id
    remoteRef:
      key: secret/sample-id
