apiVersion: external-secrets.io/v1alpha1
kind: SecretStore

metadata:
  name: external-secrets-demo
spec:
  provider:
    azurekv:
      vaultUrl: "https://external-secrets-demo.vault.azure.net"
      authType: ManagedIdentity
