apiVersion: external-secrets.io/v1alpha1
kind: SecretStore

metadata:
  name: external-secrets-demo
spec:
  provider:
    azurekv:
      authType: ServicePrincipal
      tenantId: "1543c9b8-a1d1-4f26-bffb-1368aaeb582e"
      vaultUrl: "https://external-secrets-demo.vault.azure.net"
      authSecretRef:
        clientId:
          name: azure-secret-sp
          key: ClientID
        clientSecret:
          name: azure-secret-sp
          key: ClientSecret